name: "Release"
run-name: "Release"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc --minify \
            --baseURL "https://dev.improfans.de/"

      - name: Pack website
        run: |
          cd ./public/
          tar czf website_${{ github.ref_name }}.tar.gz ./*

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: ${{ github.ref_name }}
          files: ./public/website_${{ github.ref_name }}.tar.gz
